name: Main

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "CONFIGURE SSH Key"
        env:
          PRIVATE_KEY: ${{ secrets.TF_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: "terraform commands"
        run: |
          terraform init
          terraform plan -var digitalocean_access_token=$DIGITALOCEAN_ACCESS_TOKEN -out=tfplan
          terraform apply tfplan -var digitalocean_access_token=$DIGITALOCEAN_ACCESS_TOKEN -auto-approve
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: "Post-deployment testing"
        run: |
          terraform output -raw droplet_ip > droplet_ip.txt
          DROPLET_IP=$(cat droplet_ip.txt)
          curl -I http://DROPLET_IP