name: Main

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "setup ssh keys"
        run: echo "dummy job"

      - name: "terraform commands"
        run: |
          echo "terraform init"
          echo "terraform plan -var digitalocean_access_token=$DIGITALOCEAN_ACCESS_TOKEN"
          echo "terraform apply -var digitalocean_access_token=$DIGITALOCEAN_ACCESS_TOKEN"
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}